### ISSUE TITLE
sample-swagger with scala-logging throws java.lang.IncompatibleClassChangeError: Implementing class

### ISSUE THREAD

**Issue by kpbochenek** [typesafehub/scala-logging#33]
How to reproduce:
clone repository:
https://github.com/mhamrah/spray-swagger-sample

add in build.sbt:
"com.typesafe.scala-logging"  %%  "scala-logging" % "3.1.0",

then execute "sbt run"

Exception:
Uncaught error from thread [XXX.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[XXX]
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

**Comment by kpbochenek** [comment]
Sorry guys, issue with spray-swagger (includes old scala-logging library).
