### ISSUE TITLE
InstantiationError when running from a fat jar

### ISSUE THREAD

**Issue by concerned3rdparty** [typesafehub/scala-logging#53]
Code compiles and runs fine under sbt but i can't run it from a jar. Nothing changed in build.sbt, It always points the lines that contains "class .... extends LazyLogging". "object .... extends LazyLogging" seems fine , no problem with that.

Exception in thread "main" java.lang.InstantiationError: com.typesafe.scalalogging.Logger
        at com.typesafe.scalalogging.Logger$.apply(Logger.scala:31)
        at com.typesafe.scalalogging.LazyLogging$class.logger(Logging.scala:28)
        at io.tazi.featureengineering.FeatureEngineering.logger$lzycompute(FeatureEngineering.scala:34)
        at io.tazi.featureengineering.FeatureEngineering.logger(FeatureEngineering.scala:34)

**Comment by analytically** [comment]
Outside of this lib.
